// i18n (client). gettext-style: the Chinese source string IS the key — display sites wrap dynamic
// content in T(), and render's own UI literals are authored in English. Default 'en'; lang='zh'
// returns the key unchanged (so the original Chinese is "kept"). BR's client reuses this table.
// Unmapped strings pass through untranslated (graceful — they just show their source text).
export let lang = 'en';
export function setLang(l) { lang = l; }

const EN = {
  // elements / fusion kinds (ELEMENT_INFO names)
  '中性': 'Neutral', '火': 'Fire', '冰': 'Ice', '雷': 'Lightning', '毒': 'Poison',
  '蒸氣': 'Steam', '毒爆': 'Toxic Blast', '電漿': 'Plasma', '電霜': 'Frostvolt', '電毒': 'Venomvolt',
  '毒冰': 'Venomfrost', '土': 'Earth', '熔岩': 'Magma', '凍岩': 'Frostrock', '磁暴': 'Magnetstorm', '毒沼': 'Toxic Mire',
  // spell display names (spellDisplayName)
  '魔法飛彈': 'Magic Missile', '火球': 'Fireball', '冰箭': 'Ice Shard', '雷彈': 'Lightning Bolt', '毒彈': 'Poison Bolt',
  '蒸氣彈': 'Steam Bomb', '毒爆彈': 'Toxic Bomb', '電漿彈': 'Plasma Bolt', '電霜彈': 'Frostvolt Bolt', '電毒彈': 'Venomvolt Bolt',
  '毒冰刺': 'Venomfrost Spike', '巨石': 'Boulder', '熔岩彈': 'Magma Bolt', '磁暴彈': 'Magnetstorm Bolt', '毒沼彈': 'Mire Bolt',
  '融合飛彈': 'Fusion Bolt', '普通魔法飛彈': 'Plain Magic Missile',
  // flow names (currentFlowName)
  '蒸氣控場流': 'Steam Control', '火毒爆燃流': 'Fire-Poison Detonation', '電漿破壞流': 'Plasma Destruction',
  '電霜控場流': 'Frostvolt Control', '電毒雲流': 'Venom Cloud', '毒冰緩速流': 'Venomfrost Slow',
  '火焰燃燒流': 'Fire Burn', '冰面控場流': 'Ice Control', '雷池清場流': 'Lightning Pool', '毒霧消耗流': 'Poison Attrition',
  '危險混沌流': 'Reckless Chaos', '中性飛彈流': 'Neutral Bolt',
  // arenas (name + desc)
  '失控溫室': 'Overgrown Greenhouse', '煉金毒液地窖': 'Alchemy Venom Cellar', '淹水魔法聖壇': 'Flooded Sanctum', '崩壞訓練場': 'Crumbling Arena',
  '草地很多，火焰會快速形成大片火場。': 'Lots of grass — fire spreads into huge blazes fast.',
  '毒霧與毒蟲更多，火元素很容易引發連鎖爆炸。': 'More poison clouds and bugs; fire easily triggers chain explosions.',
  '水池很多，雷鏈很強；冰元素也能把水面凍成滑冰場。': 'Lots of water — lightning chains hard; ice freezes pools into slippery rinks.',
  '薄牆很多，爆炸與衝鋒可以改變戰場路線。': 'Lots of thin walls — explosions and charges reshape the battlefield.',
  // secondaries
  '冰牆': 'Ice Wall', '土牆': 'Earth Wall', '潑油': 'Oil Slick', '黑洞': 'Black Hole',
  // upgrade chips / tags (render TAGCOLOR keys)
  '元素': 'Element', '改造': 'Mod', '副攻': 'Secondary', '通用': 'Generic', '畢業': 'Capstone',
  // misc
  '未知': 'Unknown', '未選場': 'No Arena', '元素哥布林法師': 'Elemental Goblin Mage',

  // --- upgrade / capstone cards (name) ---
  '草地蔓延': 'Grass Spread', '毒霧補給': 'Poison Resupply', '地板滲水': 'Seeping Floor', '寒霜裂縫': 'Frost Fissures',
  '暴走小怪': 'Frenzied Foes', '魔力過載': 'Mana Overload', '菁英巡邏': 'Elite Patrol',
  '注入火焰': 'Infuse Fire', '注入寒冰': 'Infuse Ice', '注入雷電': 'Infuse Lightning', '注入劇毒': 'Infuse Poison', '注入大地': 'Infuse Earth',
  '分裂': 'Split', '命中爆炸': 'Explode on Hit', '元素留痕': 'Element Trail', '快速施法': 'Fast Cast', '巨大化': 'Embiggen',
  '災難回血': 'Disaster Lifesteal', '元素蔓延': 'Element Spread', '毒爆擴大': 'Bigger Toxic Blast', '導電麻痺': 'Shock Stun',
  '大冰面': 'Bigger Ice', '寒冰碎裂': 'Ice Shatter', '危險魔力': 'Reckless Mana', '疾風步': 'Gale Step',
  '衝刺強化': 'Dash Power', '疾風連步': 'Wind Steps',
  '流星降臨': 'Meteor Storm', '瘟疫核爆': 'Plague Nuke', '磁暴奇點': 'Magnetic Singularity', '凍毒領域': 'Frost-Venom Aura',
  '電漿風暴': 'Plasma Storm', '冰川崩落': 'Glacial Collapse', '沸騰領域': 'Boiling Domain', '絕對零度': 'Absolute Zero',
  '劇毒電網': 'Venom Grid', '大地崩毀': 'Earthshatter',
  '副攻：土牆': 'Secondary: Earth Wall', '副攻：冰牆': 'Secondary: Ice Wall', '副攻：潑油': 'Secondary: Oil Slick', '副攻：黑洞': 'Secondary: Black Hole',
  '土拳・肉搏': 'Earth Fist (Melee)', '雷掌・肉搏': 'Lightning Palm (Melee)', '風掌・肉搏': 'Wind Palm (Melee)',
  '強健體魄': 'Tough Body', '迅捷': 'Swift', '回春': 'Renew',

  // --- upgrade / capstone cards (desc) ---
  '本波開始前長出更多草地。': 'More grass grows before this wave.',
  '場上多出數團毒霧，可以被火元素引爆。': 'Extra poison clouds appear — fire can detonate them.',
  '場上生成新的水池，雷鏈導電與冰面機會增加。': 'New water pools — more lightning chains and ice surfaces.',
  '場上出現冰面，衝鋒怪可能會滑倒。': 'Ice surfaces appear — chargers may slip.',
  '本波敵人更多、速度更快。': 'This wave: more enemies, and faster.',
  '本波你的傷害提高，但自傷也提高。': 'This wave: your damage up, but self-damage up too.',
  '本波額外出現一隻盾甲衝鋒怪。': 'An extra shielded charger spawns this wave.',
  '把目前魔法飛彈改造成火球；若已有冰，會融合成蒸氣彈。': 'Turns your spell into a Fireball; with Ice it fuses into a Steam Bomb.',
  '把目前魔法飛彈改造成冰箭；若已有火，會融合成蒸氣彈。': 'Turns your spell into an Ice Shard; with Fire it fuses into a Steam Bomb.',
  '把目前魔法飛彈改造成雷彈；命中水池會導電。': 'Turns your spell into a Lightning Bolt; conducts through water.',
  '把目前魔法飛彈改造成毒彈；若已有火，會融合成毒爆彈。': 'Turns your spell into a Poison Bolt; with Fire it fuses into a Toxic Bomb.',
  '把目前魔法飛彈改造成巨石：重擊擊退、打碎薄牆、迸出碎石；與火/冰/雷/毒融合成熔岩/凍岩/磁暴/毒沼。': 'Turns your spell into a Boulder: heavy knockback, smashes thin walls, scatters rock; fuses with Fire/Ice/Lightning/Poison into Magma/Frostrock/Magnetstorm/Mire.',
  '目前魔法飛彈變成多發，適合擴大元素災難。': 'Your spell fires multiple bolts — good for spreading the chaos.',
  '目前魔法飛彈命中或撞牆時會爆炸。': 'Your spell explodes on hit or wall impact.',
  '飛行路徑會留下目前元素的殘留區域。': 'Leaves a trail of your current element along its path.',
  '主攻擊冷卻降低 25%。': 'Main-attack cooldown −25%.',
  '半徑、傷害、反應範圍提高（飛彈／拳／衝刺／災難都吃）。': 'Bigger radius, damage and reaction range (bolt / punch / dash / disaster all benefit).',
  '引爆毒霧或擊殺敵人時，少量回血。': 'Heal a little when you detonate poison or kill a foe.',
  '火焰、毒霧、蒸氣等區域效果更大。': 'Fire, poison and steam ground effects are larger.',
  '毒霧被點燃時，爆炸範圍與傷害提高。': 'When poison ignites, its blast radius and damage increase.',
  '雷電導通水池時更容易打斷衝鋒怪。': 'Electrified water interrupts chargers more easily.',
  '冰元素凍水範圍提高，緩速時間增加。': 'Ice freezes a wider area and slows for longer.',
  '被冰系飛彈緩速的敵人死亡時會小範圍冰爆。': 'Foes slowed by ice burst into a small ice blast on death.',
  '所有傷害大幅提高，但自傷也提高。': 'All damage way up — but self-damage up too.',
  '衝刺冷卻降低 30%。': 'Dash cooldown −30%.',
  '衝刺傷害、擊退與元素留痕提高（衝刺流派）。': 'Dash damage, knockback and element trail up (dash build).',
  '衝刺多一段充能，可連續衝刺（雙閃/三閃）。': 'An extra dash charge — chain dashes (double / triple).',
  '畢業大絕（火+土）：戰鬥中持續天降流星，落點預警後爆炸並留下岩漿池。': 'Capstone (Fire+Earth): meteors keep falling in battle — telegraphed, then explode and leave lava pools.',
  '畢業大絕（火+毒）：你佈下的毒霧會週期性自動連環引爆（距你太近的不引爆）。': 'Capstone (Fire+Poison): your poison clouds periodically chain-detonate (not the ones hugging you).',
  '畢業大絕（土+雷）：週期生成磁力奇點把敵人吸成一團，塌縮時雷鏈貫穿引爆。': 'Capstone (Earth+Lightning): a singularity periodically vacuums foes into a clump, then a chain-lightning rips through on collapse.',
  '畢業大絕（冰+毒）：身周凝結持續凍毒光環，範圍內敵人被冰緩並中毒。': 'Capstone (Ice+Poison): a frost-venom aura follows you — foes inside are slowed and poisoned.',
  '畢業大絕（火+雷）：一顆電漿球在場上自走，週期爆裂並雷鏈導電，獵殺敵人。': 'Capstone (Fire+Lightning): a roaming plasma orb hunts foes, bursting and conducting as it goes.',
  '畢業大絕（土+冰）：週期在敵群外圍升起冰牆短暫關籠，隨即同時碎裂成大範圍冰爆。': 'Capstone (Earth+Ice): ice walls cage a foe cluster, then shatter into a wide ice blast.',
  '畢業大絕（火+冰）：全場籠罩蒸氣風暴，所有敵人持續減速並被灼燒。': 'Capstone (Fire+Ice): an arena-wide steam storm — every foe is constantly slowed and scalded.',
  '畢業大絕（雷+冰）：週期釋放冰凍新星，凍結並電擊全場敵人。': 'Capstone (Lightning+Ice): a periodic ice nova freezes and electrocutes the whole field.',
  '畢業大絕（雷+毒）：身周展開帶電毒場，範圍內敵人持續中毒並週期麻痺。': 'Capstone (Lightning+Poison): a charged poison field around you — foes inside are poisoned and periodically stunned.',
  '畢業大絕（土+毒）：腳下毒沼持續擴張，範圍內中毒陷足，並不斷迸出碎石擊退敵人、砸穿薄牆。': 'Capstone (Earth+Poison): an expanding poison quagmire — foes are poisoned and bogged, and erupting rocks knock them back and smash thin walls.',
  '副攻改成土牆，更耐久、可被爆炸炸開重塑戰場。': 'Secondary becomes an Earth Wall — durable, blasted open to reshape the field.',
  '副攻改成冰牆，遇火融成蒸氣、附近減速。': 'Secondary becomes an Ice Wall — melts to steam in fire, slows nearby foes.',
  '副攻改成潑油；油遇火會大範圍爆燃（佈場縱火流）。': 'Secondary becomes an Oil Slick — ignites into a wide blaze (arson build).',
  '副攻改成黑洞；吸聚敵人與災難後塌縮爆炸。': 'Secondary becomes a Black Hole — pulls foes and hazards together, then collapses.',
  '主攻擊改成近戰土拳：點擊出拳（短而重、附帶當前元素），長按蓄力放「裂地上勾拳」把敵人擊飛、裂地破牆。重選→升星，★2 震波、★3 週期地震。': 'Main attack becomes a melee Earth Fist: tap to punch (short, heavy, carries your element); HOLD to charge the Earthsplitter Uppercut — launches foes and rips a fissure through walls. Re-pick to star up — ★2 shockwave, ★3 periodic earthquake.',
  '主攻擊改成「雷步閃現」：點擊瞬間穿越最近敵人到身後（上雷印＋連鎖＋釘住、不擊退）；長按蓄力放「雷閃穿刺」：在範圍內連續閃現穿刺最多3名（★更多）各放電留雷印，再閃回原點＋終點電爆（過水導電、全程無敵）。衝刺穿過帶雷印的敵人會引爆雷爆。踩水放電（也會電到自己）。重選→升星，雷鏈更強、★3 雷神週期放電。': 'Main attack becomes Lightning Step (The Flash): TAP to blink through the nearest foe to the far side (mark + chain + pinned, no knockback); HOLD to charge the Lightning Lance — flash-strike the nearest foes in range (up to 3, ★ more), zapping + marking each, then blink HOME with a blast (conducts through water, invulnerable throughout). Dash through a marked foe to detonate it. Electrifies water (shocks you too). Re-pick to star up — fiercer chains, ★3 periodic Thunder God discharge.',
  '主攻擊改成近戰風掌：點擊錐形擊退、把火/毒/蒸氣往前吹；長按蓄力放「真空掌」先吸引聚怪再一掌氣爆吹飛（Boss 只硬直）。E 撿取／齊射，放棄遠程飛彈。重選→升星，一次可撿更多並齊射。': 'Main attack becomes a melee Wind Palm: TAP for a cone knockback that blows fire/poison/steam forward; HOLD to charge the Vacuum Palm — suck foes/props/clouds in, then a radial airburst blows them away (Boss is only briefly stunned). E to grab/volley. No projectile. Re-pick to star up — hold and volley more pickups.',
  '最大生命 +25，並立即回復同等生命。': 'Max HP +25, and heal that much now.',
  '移動速度 +12%。': 'Move speed +12%.',
  '立即回復 40% 最大生命。': 'Heal 40% of max HP now.',

  // --- spell descriptions (spellDescription) ---
  '中性傷害，穩定但不會觸發元素反應。': 'Neutral damage — steady, but triggers no elemental reactions.',
  '點燃草地與敵人，可引爆毒霧。': 'Ignites grass and foes; can detonate poison clouds.',
  '緩速敵人，命中水池會凍成冰面。': 'Slows foes; freezes water it hits into ice.',
  '命中敵人會連鎖，打到水池會導電。': 'Chains between foes; electrifies water it hits.',
  '命中後留下毒霧，適合佈置陷阱。': 'Leaves a poison cloud on hit — good for traps.',
  '命中產生蒸氣雲，緩速並融化冰面，能遮住戰場。': 'Spawns steam clouds on hit — slows, melts ice, and obscures the field.',
  '火毒融合，毒霧更容易爆燃，命中會製造連鎖爆炸。': 'Fire+Poison fusion — poison ignites more easily, hits cause chain explosions.',
  '火雷融合，命中爆裂並導電，清場強但自傷危險。': 'Fire+Lightning fusion — bursts and conducts on hit; great clear, risky self-damage.',
  '雷冰融合，導電與緩速並存，適合控住衝鋒怪。': 'Lightning+Ice fusion — conduct and slow together; great for locking down chargers.',
  '雷毒融合，產生帶電毒雲，持續傷害與連鎖兼具。': 'Lightning+Poison fusion — charged poison clouds with both DoT and chains.',
  '冰毒融合，緩速並留下毒性冰刺，控場穩定。': 'Ice+Poison fusion — slows and leaves toxic ice spikes; steady control.',
  '巨石彈，重擊擊退、打碎薄牆，落地迸出碎石。': 'Boulder bolt — heavy knockback, smashes thin walls, scatters rock on landing.',
  '土火融合，重擊後留下大片岩漿火池，焚燒兼控場。': 'Earth+Fire fusion — heavy hits leave wide lava pools; burn and control.',
  '土冰融合，重擊強化減速，凍住水面、破薄牆。': 'Earth+Ice fusion — heavy hits slow harder, freeze water, smash thin walls.',
  '土雷融合，命中磁力吸引周圍敵人聚成一團再雷鏈。': 'Earth+Lightning fusion — hits magnetically pull foes into a clump, then chain-lightning.',
  '土毒融合，落地生成減速且持續中毒的毒沼。': 'Earth+Poison fusion — lands as a slowing, poisoning mire.',
  '未知融合，會造成不穩定的元素災難。': 'Unknown fusion — unstable elemental chaos.',
  // mastery descriptions (masteryDesc)
  '火焰精通：每級提升火球傷害、火場範圍與燃燒強度。': 'Fire Mastery: each level boosts fireball damage, fire-zone size and burn intensity.',
  '寒冰精通：每級提升緩速時間、冰面範圍與傷害。': 'Ice Mastery: each level boosts slow duration, ice-surface size and damage.',
  '雷電精通：每級增加雷鏈跳數與導電強度。': 'Lightning Mastery: each level adds chain jumps and conduction strength.',
  '劇毒精通：每級擴大毒霧範圍、提升毒傷與毒爆。': 'Poison Mastery: each level widens poison clouds and boosts poison damage and blasts.',
  '大地精通：每級提升巨石撞擊傷害、碎石與擊退。': 'Earth Mastery: each level boosts boulder impact damage, debris and knockback.',
  '強化目前元素。': 'Strengthen your current element.',
  '副攻強化：範圍/耐久更大，冷卻更短。': 'Secondary up: bigger area / durability, shorter cooldown.',

  // --- boss banners / phase / labels ---
  'BOSS 擊破！': 'BOSS DOWN!', 'Boss 前恢復': 'Pre-boss heal', 'Boss 已擊敗': 'Boss defeated', 'Boss 爆散': 'Boss shattered',
  'Boss 登場：元素哥布林法師！': 'Boss appears: Elemental Goblin Mage!', 'Boss 進入第二階段：元素失控！': 'Boss phase 2: elements unleashed!',
  'Boss火圈': 'Boss fire ring', '元素區域開始失控！': 'Elemental zones going wild!', '元素失控：預警更短、連招更多': 'Chaos: shorter telegraphs, more combos',
  '你擊敗了元素哥布林法師！': 'You defeated the Elemental Goblin Mage!', '第二階段：連續元素災難': 'Phase 2: relentless elemental disasters',
  '菁英擊破！': 'Elite down!', '觀察 Boss 預警圈': 'Watch the boss telegraph rings',
  '先看地上的預警圈：毒、火、雷、水會連續改變戰場。': 'Watch the telegraph rings: poison/fire/lightning/water keep reshaping the field.',
  // --- toasts ---
  '主攻換成雷掌！': 'Main attack: Lightning Palm!', '主攻換成風掌！': 'Main attack: Wind Palm!', '你成了肉搏戰士！': "You're a melee brawler now!",
  '你變強了，也更危險了！': 'Stronger — and more dangerous!', '冰凍敵人會碎裂！': 'Frozen foes shatter!', '威能變大了！': 'Bigger power!',
  '施法速度提升！': 'Cast speed up!', '回復生命！': 'Healed!', '毒霧變得更危險！': 'Poison clouds got nastier!', '混亂正在餵養你！': 'Chaos is feeding you!',
  '電流開始麻痺敵人！': 'Shocks now stun foes!', '腳程變快！': 'Faster on your feet!', '衝刺多一段！': 'An extra dash charge!',
  '衝刺更頻繁了！': 'Dash more often!', '衝刺變成武器了！': 'Your dash is a weapon now!', '飛彈開始留下元素痕跡！': 'Your bolt leaves an element trail!',
  '體質增強！': 'Toughened up!', '魔法飛彈開始分裂！': 'Your bolt splits!',
  '流星降臨！從此天降災厄': 'Meteor Storm! Doom rains from the sky', '瘟疫核爆！毒霧開始自爆': 'Plague Nuke! Your poison self-detonates',
  '磁暴奇點！敵人將被吸攏電穿': 'Magnetic Singularity! Foes pulled in and zapped', '凍毒領域！身周凝結劇毒寒霜': 'Frost-Venom Aura! Toxic frost coils around you',
  '電漿風暴！電漿球開始獵殺': 'Plasma Storm! The orb starts hunting', '冰川崩落！冰牆將困敵碎裂': 'Glacial Collapse! Ice walls cage and shatter',
  '沸騰領域！全場沸騰蒸騰': 'Boiling Domain! The whole arena boils', '絕對零度！全場將被凍結電穿': 'Absolute Zero! The field freezes and shocks',
  '劇毒電網！身周張開帶電毒場': 'Venom Grid! A charged poison field opens', '大地崩毀！腳下毒沼蔓延崩裂': 'Earthshatter! A mire spreads and the ground cracks',
  '冰川崩落！冰牆將困敵碎裂 ': 'Glacial Collapse! Ice walls cage and shatter',
  // --- floating combat text ---
  '抓起 ↑': 'Grab ↑', '投擲 →': 'Throw →', '拔起冰牆 ↑': 'Pull ice wall ↑', '拔起薄牆 ↑': 'Pull wall ↑', '舉起 ↑': 'Lift ↑',
  '撞牆!': 'Wall slam!', '撞牆暈眩！': 'Wall-stunned!', '岩漿！': 'Magma!', '冰爆！': 'Ice blast!', '冰凍水池': 'Frozen pool',
  '冰面滑倒！': 'Slipped on ice!', '冰面融化': 'Ice melted', '冰川崩落！': 'Glacial Collapse!', '水池導電': 'Water shock', '水池導電！': 'Water electrified!',
  '水池結冰！': 'Water froze!', '水池開始結成大片冰面！': 'Water freezing into a sheet!', '油爆': 'Oil blast', '流星！': 'Meteor!', '燙手': 'Hot!',
  '盾甲怪冰面滑倒': 'Charger slipped on ice', '瞬閃': 'Blink', '碎片': 'Shards', '磁暴吸引！': 'Magnetic pull!', '絕對零度！': 'Absolute Zero!',
  '地震！': 'Earthquake!', '地震': 'Earthquake', '超新星': 'Supernova', '超新星！': 'Supernova!', '雷擊': 'Lightning', '雷擊麻痺！': 'Shock stun!',
  '雷擊！': 'Lightning!', '雷神！': 'Thunder God!', '雷鏈落空': 'Chain fizzled', '電毒雲！': 'Venom cloud!', '電漿爆炸': 'Plasma blast',
  '電霧！': 'Shock mist!', '蒸氣！': 'Steam!', '蓄力！': 'Charging!', '毒瓶': 'Poison flask', '毒瓶預備': 'Poison flask incoming', '毒瓶！': 'Poison flask!',
  '毒霧爆燃': 'Poison ignites', '召喚小怪！': 'Summon minions!', '召喚水池': 'Summon pool', '黑洞塌縮': 'Black hole collapse', '緩速': 'Slow',
  '撞牆': 'Wall slam', '震波': 'Shockwave', '肉搏': 'Melee', '充能': 'Charged', '土拳': 'Earth Fist', '雷掌': 'Lightning Palm', '風掌': 'Wind Palm',
  '雷爆!': 'Zap!', '雷步穿身': 'Lightning Step', '風助火勢': 'Fanned flames', '撞牆!': 'Wall slam!', '燒!': 'Burn!', '裂地上勾拳': 'Earthsplitter Uppercut', '雷閃穿刺': 'Lightning Lance', '真空掌': 'Vacuum Palm',
  '命中會爆炸！': 'Now explodes on hit!',
  // --- damage sources / entities ---
  '元素哥布林撞擊': 'Goblin Mage hit', '史萊姆撞擊': 'Slime hit', '毒蟲撞擊': 'Bug hit', '火焰小鬼撞擊': 'Imp hit', '火焰小鬼': 'Fire Imp',
  '盾甲衝撞': 'Charger ram', '飛人撞擊': 'Flung-foe hit', '火焰地板': 'Fire floor', '友方火焰區': 'Friendly fire zone',
  // --- boss attack labels (telegraph warnings) ---
  '大火圈：橘圈會燃燒地板': 'Big fire ring: orange rings burn the floor', '大範圍導電：離開水池': 'Wide shock: leave the water',
  '毒火連爆：紫圈後面接火圈': 'Poison-fire combo: fire follows the purple ring', '毒瓶：離開紫色落點': 'Poison flask: leave the purple target',
  '水雷連招': 'Water-shock combo', '水雷連招：水池會被雷擊導電': 'Water-shock combo: pools get electrified',
  '火圈': 'Fire ring', '火圈預備': 'Fire ring incoming', '火圈！': 'Fire ring!', '火圈：不要站在橘色圈內': "Fire ring: don't stand in the orange",
  '電霧：蒸氣後接雷擊': 'Shock mist: lightning after steam',
  // --- misc / stat fallbacks ---
  '尚未命中 Boss': 'No boss hits yet', '尚未發生': 'None yet', '未知災難': 'Unknown disaster', '未知競技場': 'Unknown arena', '無': 'none',
  '無事件': 'no events', '無升級': 'no upgrades', '無災難': 'no disasters',
  // --- death-message templates (composed in sim with a source after 死因：) ---
  '你倒在元素哥布林法師的元素連招中。死因：': 'Cut down by the Elemental Goblin Mage. Cause: ',
  '你被怪物逼入混亂地形後擊倒。死因：': 'Cornered into chaotic terrain and struck down. Cause: ',
  '你被自己的魔法災難吞掉了。死因：': 'Swallowed by your own magical disaster. Cause: ',
  '魔法失控，地牢吞沒了你。死因：': 'Magic ran wild and the dungeon took you. Cause: '
};

export function T(s) { if (lang === 'zh' || s == null) return s; return (s in EN) ? EN[s] : s; }
