import puppeteer from 'puppeteer';
const B = await puppeteer.launch({ headless: 'new', protocolTimeout: 180000, args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const page = await B.newPage();
await page.setViewport({ width: 1280, height: 720 });
const errs=[]; page.on('pageerror', e => errs.push('PAGE '+e.message)); page.on('console', m => { if (m.type()==='error') errs.push('CON '+m.text()); });
await page.evaluateOnNewDocument(() => { try { localStorage.setItem('mmm_v2_played','1'); } catch {} });
await page.goto('http://localhost:8099/v2.html?turbo=8', { waitUntil: 'networkidle0' });
await page.waitForFunction('window.__v2 && window.__lab && __gl', { timeout: 20000 });
await page.evaluate(() => { const v=__v2; v.v2s.introT=0; v.fighters[1].ai=false;
  v.fighters[0].x=430; v.fighters[0].y=330; v.fighters[1].x=560; v.fighters[1].y=330;
  v.fighters[0].item='wind'; v.fighters[0].itemUses=3; v.fighters[1].stability=42; });
const ok = await page.waitForFunction(`window.__hud && __hud.cards[0].portrait === 'glb' && __hud.cards[1].portrait === 'glb'`, { timeout: 20000 }).then(()=>true).catch(()=>false);
console.log('GLB 頭像快照:', ok, JSON.stringify(await page.evaluate('window.__hud')));
console.log('errs:', errs.slice(0,5));
await page.screenshot({ path: '/tmp/hud_full.png' });
await B.close();
